-- 关系联合唯一；取消点赞/收藏可物理删除。阅读历史与权益、收藏相互独立。
CREATE TABLE publication_reactions (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id bigint NOT NULL REFERENCES users(id), publication_id bigint NOT NULL REFERENCES publications(id),
 kind varchar(16) NOT NULL CHECK(kind IN ('BOOKMARK','LIKE')), created_at timestamptz NOT NULL DEFAULT now(),
 UNIQUE(user_id,publication_id,kind)
);
CREATE INDEX publication_reactions_count_idx ON publication_reactions(publication_id,kind);
CREATE INDEX publication_reactions_user_idx ON publication_reactions(user_id,kind,created_at DESC,id DESC);
CREATE TABLE publication_reading_progress (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id bigint NOT NULL REFERENCES users(id), publication_id bigint NOT NULL REFERENCES publications(id),
 version varchar(32) NOT NULL, position varchar(120) NOT NULL DEFAULT '', percent integer NOT NULL CHECK(percent BETWEEN 0 AND 100),
 updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(user_id,publication_id)
);
CREATE INDEX publication_reading_user_idx ON publication_reading_progress(user_id,updated_at DESC,id DESC);
