-- 事件留存独立于当前点赞/收藏关系；取消操作不删除历史事件。
CREATE TABLE publication_events (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 publication_id bigint NOT NULL REFERENCES publications(id),
 user_id bigint REFERENCES users(id),
 kind varchar(16) NOT NULL CHECK(kind IN ('VIEW','SHARE','LIKE','BOOKMARK')),
 dedup_key varchar(160) NOT NULL,
 created_at timestamptz NOT NULL DEFAULT now(),
 UNIQUE(publication_id,kind,dedup_key)
);
CREATE INDEX publication_events_count_idx ON publication_events(publication_id,kind);
CREATE INDEX publication_events_feed_idx ON publication_events(created_at DESC,id DESC) WHERE kind <> 'VIEW' AND user_id IS NOT NULL;
