-- 单篇分享授权不等于账号会话。分享人和文章唯一，重复复制不生成新授权或新计数。
CREATE TABLE publication_shares (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 publication_id bigint NOT NULL REFERENCES publications(id),
 user_id bigint NOT NULL REFERENCES users(id),
 token varchar(43) NOT NULL UNIQUE,
 created_at timestamptz NOT NULL DEFAULT now(),
 UNIQUE(user_id,publication_id)
);
