-- 社区动态独立于文章统计：以来源事件键去重，跨业务目标不建立错误的单一外键。
CREATE TABLE community_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_key varchar(160) NOT NULL UNIQUE,
    actor_id bigint NOT NULL REFERENCES users(id),
    kind varchar(64) NOT NULL,
    subject_type varchar(32) NOT NULL,
    subject_id varchar(160) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX community_events_feed_idx ON community_events(created_at DESC,id DESC);
CREATE INDEX community_events_subject_idx ON community_events(subject_type,subject_id);
-- 保留已有动态，阅读埋点不进入公开动态流。旧表继续承担文章计数与去重。
INSERT INTO community_events(event_key,actor_id,kind,subject_type,subject_id,created_at)
SELECT 'publication-event:' || id, user_id, 'PUBLICATION_' || kind, 'PUBLICATION', publication_id::text, created_at
FROM publication_events WHERE user_id IS NOT NULL AND kind <> 'VIEW'
ON CONFLICT(event_key) DO NOTHING;
