CREATE TABLE categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug varchar(80) NOT NULL UNIQUE,
    name varchar(80) NOT NULL,
    sort_order integer NOT NULL DEFAULT 0
);

CREATE TABLE cases (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id bigint NOT NULL REFERENCES categories(id),
    slug varchar(120) NOT NULL UNIQUE,
    title varchar(160) NOT NULL,
    summary varchar(500) NOT NULL,
    access_type varchar(10) NOT NULL CHECK (access_type IN ('FREE', 'PAID')),
    price_minor bigint NOT NULL DEFAULT 0 CHECK (price_minor >= 0),
    currency char(3) NOT NULL DEFAULT 'CNY' CHECK (currency = 'CNY'),
    status varchar(16) NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')),
    delivery_status varchar(16) NOT NULL DEFAULT 'AVAILABLE' CHECK (delivery_status IN ('AVAILABLE', 'SUSPENDED')),
    is_demo boolean NOT NULL DEFAULT false,
    published_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK ((access_type = 'FREE' AND price_minor = 0) OR (access_type = 'PAID' AND price_minor > 0)),
    CHECK (status <> 'PUBLISHED' OR published_at IS NOT NULL)
);

CREATE TABLE case_contents (
    case_id bigint PRIMARY KEY REFERENCES cases(id),
    preview_markdown text NOT NULL,
    full_markdown text NOT NULL,
    requirements text NOT NULL,
    deliverables text NOT NULL,
    version varchar(32) NOT NULL DEFAULT '1.0',
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX cases_published_idx ON cases (published_at DESC, id DESC)
    WHERE status = 'PUBLISHED' AND delivery_status = 'AVAILABLE';
CREATE INDEX cases_category_idx ON cases (category_id, published_at DESC, id DESC)
    WHERE status = 'PUBLISHED' AND delivery_status = 'AVAILABLE';
