ALTER TABLE categories
    ADD COLUMN created_at timestamptz NOT NULL DEFAULT now(),
    ADD COLUMN updated_at timestamptz NOT NULL DEFAULT now(),
    ADD COLUMN is_deleted boolean NOT NULL DEFAULT false;

ALTER TABLE cases
    ADD COLUMN is_deleted boolean NOT NULL DEFAULT false;

ALTER TABLE case_contents
    ADD COLUMN created_at timestamptz NOT NULL DEFAULT now(),
    ADD COLUMN is_deleted boolean NOT NULL DEFAULT false;

CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(254) NOT NULL,
    password_hash varchar(100) NOT NULL,
    nickname varchar(40) NOT NULL,
    role varchar(16) NOT NULL DEFAULT 'USER' CHECK (role IN ('USER', 'ADMIN')),
    status varchar(16) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'DISABLED')),
    email_verified boolean NOT NULL DEFAULT false,
    last_login_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    is_deleted boolean NOT NULL DEFAULT false
);

CREATE UNIQUE INDEX users_email_unique_active_idx ON users (email)
    WHERE is_deleted = false;
CREATE INDEX users_created_at_idx ON users (created_at DESC)
    WHERE is_deleted = false;

DROP INDEX cases_published_idx;
DROP INDEX cases_category_idx;
CREATE INDEX cases_published_idx ON cases (published_at DESC, id DESC)
    WHERE status = 'PUBLISHED' AND delivery_status = 'AVAILABLE' AND is_deleted = false;
CREATE INDEX cases_category_idx ON cases (category_id, published_at DESC, id DESC)
    WHERE status = 'PUBLISHED' AND delivery_status = 'AVAILABLE' AND is_deleted = false;
