-- 评论和积分是独立业务模块。它们通过稳定的 target_type + target_key
-- 挂载内容，不把 discussion/credit 表直接外键到某一种内容表。

CREATE TABLE discussion_threads (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_type varchar(40) NOT NULL,
    target_key varchar(120) NOT NULL,
    status varchar(16) NOT NULL DEFAULT 'OPEN'
        CHECK (status IN ('OPEN', 'LOCKED', 'HIDDEN')),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    is_deleted boolean NOT NULL DEFAULT false,
    CHECK (target_type ~ '^[A-Z][A-Z0-9_]{1,39}$'),
    CHECK (length(btrim(target_key)) > 0)
);

CREATE UNIQUE INDEX discussion_threads_target_unique_active_idx
    ON discussion_threads (target_type, target_key)
    WHERE is_deleted = false;

CREATE TABLE comments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thread_id bigint NOT NULL REFERENCES discussion_threads(id),
    author_id bigint NOT NULL REFERENCES users(id),
    parent_id bigint REFERENCES comments(id),
    root_id bigint REFERENCES comments(id),
    depth smallint NOT NULL DEFAULT 0 CHECK (depth BETWEEN 0 AND 5),
    body varchar(4000) NOT NULL,
    status varchar(16) NOT NULL DEFAULT 'PUBLISHED'
        CHECK (status IN ('PUBLISHED', 'HIDDEN', 'DELETED')),
    edited_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    is_deleted boolean NOT NULL DEFAULT false,
    CHECK (length(btrim(body)) BETWEEN 1 AND 4000),
    CHECK ((depth = 0 AND parent_id IS NULL AND root_id IS NULL)
        OR (depth > 0 AND parent_id IS NOT NULL AND root_id IS NOT NULL)),
    CHECK (parent_id IS NULL OR parent_id <> id),
    CHECK (root_id IS NULL OR root_id <> id)
);

CREATE INDEX comments_thread_roots_idx
    ON comments (thread_id, created_at DESC, id DESC)
    WHERE depth = 0 AND is_deleted = false;
CREATE INDEX comments_root_tree_idx
    ON comments (root_id, created_at, id)
    WHERE root_id IS NOT NULL AND is_deleted = false;
CREATE INDEX comments_parent_idx
    ON comments (parent_id, created_at, id)
    WHERE parent_id IS NOT NULL AND is_deleted = false;

CREATE TABLE credit_accounts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL UNIQUE REFERENCES users(id),
    balance bigint NOT NULL DEFAULT 0 CHECK (balance >= 0),
    version bigint NOT NULL DEFAULT 0 CHECK (version >= 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    is_deleted boolean NOT NULL DEFAULT false
);

-- 账户余额是读取优化；每一次变动的事实以只追加的积分流水为准。
CREATE TABLE credit_ledger_entries (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id bigint NOT NULL REFERENCES credit_accounts(id),
    entry_type varchar(20) NOT NULL
        CHECK (entry_type IN ('GRANT', 'TOP_UP', 'SPEND', 'REFUND', 'ADJUSTMENT', 'EXPIRE')),
    amount bigint NOT NULL CHECK (amount <> 0),
    balance_after bigint NOT NULL CHECK (balance_after >= 0),
    reference_type varchar(40) NOT NULL,
    reference_key varchar(120) NOT NULL,
    idempotency_key varchar(120) NOT NULL UNIQUE,
    note varchar(500),
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    CHECK (length(btrim(reference_type)) > 0),
    CHECK (length(btrim(reference_key)) > 0),
    CHECK (length(btrim(idempotency_key)) > 0),
    CHECK ((entry_type IN ('GRANT', 'TOP_UP', 'REFUND') AND amount > 0)
        OR (entry_type IN ('SPEND', 'EXPIRE') AND amount < 0)
        OR entry_type = 'ADJUSTMENT')
);

CREATE INDEX credit_ledger_account_time_idx
    ON credit_ledger_entries (account_id, created_at DESC, id DESC);
CREATE INDEX credit_ledger_reference_idx
    ON credit_ledger_entries (reference_type, reference_key, created_at DESC);

CREATE TABLE credit_offers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_type varchar(40) NOT NULL,
    target_key varchar(120) NOT NULL,
    credit_price bigint NOT NULL CHECK (credit_price > 0),
    status varchar(16) NOT NULL DEFAULT 'ACTIVE'
        CHECK (status IN ('ACTIVE', 'INACTIVE')),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    is_deleted boolean NOT NULL DEFAULT false,
    CHECK (length(btrim(target_type)) > 0),
    CHECK (length(btrim(target_key)) > 0)
);

CREATE UNIQUE INDEX credit_offers_target_unique_active_idx
    ON credit_offers (target_type, target_key)
    WHERE is_deleted = false;

CREATE TABLE content_entitlements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id),
    target_type varchar(40) NOT NULL,
    target_key varchar(120) NOT NULL,
    source_ledger_entry_id bigint REFERENCES credit_ledger_entries(id),
    status varchar(16) NOT NULL DEFAULT 'ACTIVE'
        CHECK (status IN ('ACTIVE', 'REVOKED')),
    granted_at timestamptz NOT NULL DEFAULT now(),
    revoked_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    is_deleted boolean NOT NULL DEFAULT false,
    CHECK (length(btrim(target_type)) > 0),
    CHECK (length(btrim(target_key)) > 0),
    CHECK ((status = 'ACTIVE' AND revoked_at IS NULL)
        OR (status = 'REVOKED' AND revoked_at IS NOT NULL))
);

CREATE UNIQUE INDEX content_entitlements_user_target_active_idx
    ON content_entitlements (user_id, target_type, target_key)
    WHERE status = 'ACTIVE' AND is_deleted = false;
CREATE INDEX content_entitlements_target_idx
    ON content_entitlements (target_type, target_key, user_id)
    WHERE status = 'ACTIVE' AND is_deleted = false;
