-- 积分模型简化：V3 建的四张表里，credit_accounts 把余额藏在用户之外的中转表后面，
-- credit_offers 把 Publication 自己的价格存到另一张表再每次 LEFT JOIN 取回。
-- 这里把余额和价格放回它们真正所属的行，只保留流水（幂等事实）和权益（功能必需）。

-- 先把价格搬回 publications —— 必须在 DROP credit_offers 之前执行。
ALTER TABLE publications ADD COLUMN credit_price bigint NOT NULL DEFAULT 0;

UPDATE publications p
SET credit_price = offer.credit_price
FROM credit_offers offer
WHERE offer.target_type = 'PUBLICATION'
  AND offer.target_key = p.slug
  AND offer.status = 'ACTIVE'
  AND offer.is_deleted = false;

-- 价格回到本表后，这张表没有别的信息了。
-- 删除顺序：先删被引用的子表，再删父表（ledger 和 unlocks 都指向 credit_accounts）。
DROP TABLE content_entitlements;
DROP TABLE credit_ledger_entries;
DROP TABLE credit_offers;
DROP TABLE credit_accounts;

-- 余额放回 users。扣减因此可以是一条原子语句：
--   UPDATE users SET credit_balance = credit_balance - :cost
--   WHERE id = :id AND credit_balance >= :cost
-- 0 行即余额不足，不再需要 version 乐观锁和 CAS 重试循环。
ALTER TABLE users ADD COLUMN credit_balance bigint NOT NULL DEFAULT 0;
ALTER TABLE users ADD CONSTRAINT users_credit_balance_check CHECK (credit_balance >= 0);

-- 恢复 V4 丢掉的访问类型与价格一致性约束（当时 price_minor 被删，约束没重建，
-- 只剩 Publication.validate() 在 Java 里守着，数据库层没有对等保护）。
ALTER TABLE publications ADD CONSTRAINT publications_credit_price_check
    CHECK ((access_type = 'FREE' AND credit_price = 0)
        OR (access_type = 'CREDIT' AND credit_price > 0));

-- V4 写的注释指向已被删除的 credit_offers，这里重新覆盖。
COMMENT ON COLUMN publications.access_type IS 'FREE 或 CREDIT；CREDIT 内容的价格见 publications.credit_price';
COMMENT ON COLUMN users.credit_balance IS '当前可用积分；扣减使用带余额校验的原子 UPDATE，事实以 credit_ledger_entries 为准';

-- 流水：只追加的事实记录，是支付回调幂等和用户申诉的唯一依据。
-- user_id 取代原来的 account_id 中转，否则删掉 credit_accounts 后流水无法对回用户。
-- 刻意不继承 BasePO 那套审计列：账本没有"更新"和"逻辑删除"这两种状态。
CREATE TABLE credit_ledger_entries (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id),
    delta bigint NOT NULL CHECK (delta <> 0),
    balance_after bigint NOT NULL CHECK (balance_after >= 0),
    reason varchar(24) NOT NULL
        CHECK (reason IN ('GRANT', 'TOP_UP', 'SPEND', 'REFUND', 'ADJUSTMENT', 'EXPIRE')),
    reference_key varchar(120) NOT NULL,
    idempotency_key varchar(120) NOT NULL UNIQUE,
    note varchar(500),
    created_at timestamptz NOT NULL DEFAULT now(),
    CHECK (length(btrim(reference_key)) > 0),
    CHECK (length(btrim(idempotency_key)) > 0),
    -- 金额符号与业务原因必须一致：增加为正，消费和过期必然为负。
    CHECK ((reason IN ('GRANT', 'TOP_UP', 'REFUND') AND delta > 0)
        OR (reason IN ('SPEND', 'EXPIRE') AND delta < 0)
        OR reason = 'ADJUSTMENT')
);

CREATE INDEX credit_ledger_user_time_idx
    ON credit_ledger_entries (user_id, created_at DESC, id DESC);
CREATE INDEX credit_ledger_reference_idx
    ON credit_ledger_entries (reference_key, created_at DESC);

-- 权益：某个用户是否拥有某个内容。无法从余额推导，删了功能就坏了。
CREATE TABLE content_unlocks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id),
    publication_id bigint NOT NULL REFERENCES publications(id),
    credits_paid bigint NOT NULL CHECK (credits_paid > 0),
    source_ledger_entry_id bigint REFERENCES credit_ledger_entries(id),
    granted_at timestamptz NOT NULL DEFAULT now(),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    is_deleted boolean NOT NULL DEFAULT false
);

CREATE UNIQUE INDEX content_unlocks_user_publication_active_idx
    ON content_unlocks (user_id, publication_id)
    WHERE is_deleted = false;
CREATE INDEX content_unlocks_publication_idx
    ON content_unlocks (publication_id, user_id)
    WHERE is_deleted = false;
