-- 评论扁平化 + 点赞。
--
-- 原先回复可以无限嵌套（V5 取消了 5 层上限），服务层用递归组装整棵树：
-- 递归深度等于回复链长度，是用户可以构造的 StackOverflow，且响应体无上界。
-- 改为单层：根评论分页，其下回复平铺，回复的回复用 parent_id 表达「回复 @某人」。

-- 深度收敛到 0..1。既有 depth > 1 的行拍平到第一层：
-- root_id 已经指向根评论（不变），parent_id 保留（保住「回复 @某人」的语义），只把 depth 归一。
UPDATE comments SET depth = 1 WHERE depth > 1;

ALTER TABLE comments DROP CONSTRAINT comments_depth_non_negative_check;
ALTER TABLE comments ALTER COLUMN depth TYPE smallint;
ALTER TABLE comments ADD CONSTRAINT comments_depth_check CHECK (depth BETWEEN 0 AND 1);

-- 点赞计数反规范化到 comments：热门/综合排序必须在分页之前就有 like_count，
-- 否则排序的只是当前页。回复数不冗余——它只用于展示，随预览查询按页算出，不会漂移。
ALTER TABLE comments ADD COLUMN like_count integer NOT NULL DEFAULT 0;
ALTER TABLE comments ADD CONSTRAINT comments_like_count_check CHECK (like_count >= 0);

CREATE TABLE comment_likes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_id bigint NOT NULL REFERENCES comments(id),
    user_id bigint NOT NULL REFERENCES users(id),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    is_deleted boolean NOT NULL DEFAULT false
);

-- 一个用户对一条评论至多一个有效点赞。
CREATE UNIQUE INDEX comment_likes_comment_user_active_idx
    ON comment_likes (comment_id, user_id)
    WHERE is_deleted = false;

-- V3 建的两个偏索引是给「根评论分页 + 按 root_id 取回复」准备的，但当时的查询一次全量读取，
-- 从未用上。这里按新的查询形状重建。
DROP INDEX comments_thread_roots_idx;
DROP INDEX comments_root_tree_idx;
DROP INDEX comments_parent_idx;

CREATE INDEX comments_thread_root_latest_idx
    ON comments (thread_id, created_at DESC, id DESC)
    WHERE depth = 0 AND status = 'PUBLISHED' AND is_deleted = false;

CREATE INDEX comments_thread_root_hot_idx
    ON comments (thread_id, like_count DESC, created_at DESC, id DESC)
    WHERE depth = 0 AND status = 'PUBLISHED' AND is_deleted = false;

-- 回复读取只按 root_id 走，用来取预览和分页。
CREATE INDEX comments_root_flat_idx
    ON comments (root_id, created_at, id)
    WHERE depth = 1 AND status = 'PUBLISHED' AND is_deleted = false;
