/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Checks the actual PostgreSQL connection */
    get: operations["getHealth"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/register": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Creates a member account and signs it in */
    post: operations["register"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Signs in with email and password */
    post: operations["login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Returns the signed-in member */
    get: operations["getCurrentUser"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Invalidates the current session */
    post: operations["logout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/categories": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Categories with published and available case counts */
    get: operations["getCategories"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/cases": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Public case summaries; never includes body content */
    get: operations["getCases"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/cases/{slug}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Public detail and preview; never includes full body */
    get: operations["getCase"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/cases/{id}/content": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Only published and available FREE cases are readable in M1 */
    get: operations["getCaseContent"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @enum {string} */
    AccessType: "FREE" | "PAID";
    Category: {
      /** @description PostgreSQL bigint ID serialized as a string. */
      id: string;
      slug: string;
      name: string;
      /** Format: int64 */
      caseCount: number;
    };
    CaseSummary: {
      /** @description PostgreSQL bigint ID serialized as a string. */
      id: string;
      slug: string;
      title: string;
      summary: string;
      categorySlug: string;
      categoryName: string;
      accessType: components["schemas"]["AccessType"];
      /** Format: int64 */
      priceMinor: number;
      /** @enum {string} */
      currency: "CNY";
      isDemo: boolean;
      /** Format: date-time */
      publishedAt: string;
    };
    Preview: {
      previewMarkdown: string;
      requirements: string;
      deliverables: string;
      version: string;
      /** Format: date-time */
      updatedAt: string;
    };
    CaseDetail: {
      caseInfo: components["schemas"]["CaseSummary"];
      preview: components["schemas"]["Preview"];
    };
    CaseContent: {
      /** @description PostgreSQL bigint ID serialized as a string. */
      caseId: string;
      markdown: string;
      version: string;
      /** Format: date-time */
      updatedAt: string;
    };
    CasePage: {
      items: components["schemas"]["CaseSummary"][];
      page: number;
      size: number;
      /** Format: int64 */
      total: number;
      /** Format: int64 */
      totalPages: number;
    };
    RegisterRequest: {
      /** Format: email */
      email: string;
      /**
       * Format: password
       * @description Must contain at least one ASCII letter and one digit.
       */
      password: string;
      nickname: string;
    };
    LoginRequest: {
      /** Format: email */
      email: string;
      /** Format: password */
      password: string;
    };
    CurrentUser: {
      /** @description PostgreSQL bigint ID serialized as a string. */
      id: string;
      /** Format: email */
      email: string;
      nickname: string;
      /** @enum {string} */
      role: "USER" | "ADMIN";
      emailVerified: boolean;
      /** Format: date-time */
      createdAt: string;
    };
    Error: {
      code: string;
      message: string;
      requestId: string;
    };
    Health: {
      /** @enum {string} */
      status: "UP";
      /** @enum {string} */
      database: "UP";
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      200: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Health"];
        };
      };
      /** @description Unexpected server error */
      500: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Database temporarily unavailable */
      503: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  register: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterRequest"];
      };
    };
    responses: {
      /** @description Account created; session cookie is set */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CurrentUser"];
        };
      };
      /** @description Invalid email, nickname or password */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Email already registered */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Signed in; session cookie is set */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CurrentUser"];
        };
      };
      /** @description Invalid request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Invalid credentials */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  getCurrentUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current member */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CurrentUser"];
        };
      };
      /** @description Not signed in */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Signed out */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not signed in */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  getCategories: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      200: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Category"][];
        };
      };
      /** @description Unexpected server error */
      500: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Database temporarily unavailable */
      503: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  getCases: {
    parameters: {
      query?: {
        page?: number;
        size?: number;
        q?: string;
        category?: string;
        access?: "" | "FREE" | "PAID";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      200: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CasePage"];
        };
      };
      /** @description Invalid query */
      400: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Unexpected server error */
      500: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Database temporarily unavailable */
      503: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  getCase: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      200: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CaseDetail"];
        };
      };
      /** @description Invalid slug */
      400: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Missing, draft, archived or suspended case */
      404: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Unexpected server error */
      500: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Database temporarily unavailable */
      503: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  getCaseContent: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      200: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CaseContent"];
        };
      };
      /** @description Invalid ID */
      400: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Paid content is locked; purchases are not implemented */
      403: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Missing, draft, archived or suspended case */
      404: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Unexpected server error */
      500: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Database temporarily unavailable */
      503: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
}
