/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Checks the actual PostgreSQL connection */
    get: operations["getHealth"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/email-codes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Sends a six-digit registration code through Resend */
    post: operations["sendEmailCode"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/register": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Creates a member account and signs it in */
    post: operations["register"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Signs in with email and password */
    post: operations["login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Returns the signed-in member */
    get: operations["getCurrentUser"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Invalidates the current session */
    post: operations["logout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/categories": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Lists category options for the content editor */
    get: operations["getAdminCategories"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/categories": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Categories with published and available publication counts */
    get: operations["getCategories"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/discussions/comments": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 按根评论分页返回讨论；每条根评论附带回复总数与前两条回复预览
     * @description 回复是单层的：所有回复平铺在其根评论下，replyCount 是精确总数。作者自删的评论以 deleted 占位保留，其下回复仍然可见。
     */
    get: operations["listComments"];
    put?: never;
    /**
     * 发表根评论，或回复某条评论
     * @description parentId 是根评论的 id；回复一条回复时仍挂在同一个根评论下，返回的 parentId 用于显示「回复 @某人」。
     */
    post: operations["createComment"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/publications": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Lists publications in every publication state */
    get: operations["getAdminPublications"];
    put?: never;
    /** Creates a draft publication and its content */
    post: operations["createAdminPublication"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/publications/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["PublicationId"];
      };
      cookie?: never;
    };
    /** Returns the complete editable publication */
    get: operations["getAdminPublication"];
    /** Replaces the editable publication fields and content */
    put: operations["updateAdminPublication"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/publications/{id}/publish": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Publishes a publication to the public catalog */
    post: operations["publishAdminPublication"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/publications/{id}/archive": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Archives a publication and removes it from the public catalog */
    post: operations["archiveAdminPublication"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/publications": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Public publication summaries; never includes body content */
    get: operations["getPublications"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/publications/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Public detail by stable database ID; legacy slug is read-only compatibility */
    get: operations["getPublication"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/publications/{id}/content": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Only published and available FREE publications are readable in M1 */
    get: operations["getPublicationContent"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/discussions/comments/{rootId}/replies": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 「展开全部回复」：分页返回某条根评论下的回复 */
    get: operations["listReplies"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/discussions/comments/{id}/like": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 切换点赞状态，返回切换后是否已点赞 */
    post: operations["toggleCommentLike"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/discussions/comments/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** 删除自己的评论；保留占位行，其下回复继续可见 */
    delete: operations["deleteComment"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/discussions/comments/{id}/hide": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 管理员隐藏评论；整条不再对外可见 */
    post: operations["hideComment"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/discussions/threads/lock": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 管理员锁定讨论；线程仍可读，但不再接受评论与回复 */
    post: operations["lockThread"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/storage/files/{id}/download-url": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a five-minute private download URL for an owned file */
    get: operations["getFileDownloadUrl"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/me/profile": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Updates the current member profile; avatar must be an owned AVATAR file */
    put: operations["updateCurrentProfile"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/me/avatar-url": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Returns an owner-only inline avatar URL, valid for five minutes */
    get: operations["getCurrentAvatarImage"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/me/avatar": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 上传当前用户头像
     * @description Requires an active session; 20 avatar uploads/user/minute. PNG/JPEG/WebP only, maximum 5 MiB, verified by the user profile use case including file headers. Returns a durable avatar file ID; PUT /users/me/profile binds it. No generic browser-selected upload purpose.
     */
    post: operations["uploadAvatar"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Search/page members without exposing credentials */
    get: operations["listAdminMembers"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/users/{id}/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Disable/restore member; revoke sessions on disable; protect admins */
    put: operations["changeMemberStatus"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/operations/overview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Persisted totals and seven-day activity */
    get: operations["getOperationsOverview"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/operations/ledger": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read actual credit movements */
    get: operations["listCreditLedger"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/discussions/comments": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Moderation queue; deleted body is redacted */
    get: operations["listModerationComments"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/media": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Image/cover 10 MiB; MP4/WebM 100 MiB; attachment 20 MiB */
    post: operations["uploadPublicationMedia"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/media/{id}/url": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Admin short-lived private media URL */
    get: operations["getAdminMediaUrl"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/publications/{publicationId}/media/{id}/url": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Published cover/preview is public; paid full media CONTENT_LOCKED; draft/unbound unavailable */
    get: operations["getPublicationMediaUrl"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/media/uploads/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Current admin upload progress: OSS acknowledged parts, never local stream reads */
    get: operations["getPublicationUploadProgress"];
    put?: never;
    post?: never;
    /** Cancel own task; stop and abort multipart at next confirmed part boundary */
    delete: operations["cancelPublicationUpload"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @enum {string} */
    AccessType: "FREE" | "CREDIT";
    Category: {
      /** @description PostgreSQL bigint ID serialized as a string. */
      id: string;
      slug: string;
      name: string;
      /** Format: int64 */
      publicationCount: number;
    };
    Preview: {
      previewMarkdown: string;
      requirements: string;
      deliverables: string;
      version: string;
      /** Format: date-time */
      updatedAt: string;
    };
    EmailCodeRequest: {
      /** Format: email */
      email: string;
      /** @enum {string} */
      purpose: "REGISTER";
    };
    EmailCodeDispatch: {
      /** Format: int64 */
      expiresInSeconds: number;
      /** Format: int64 */
      resendAfterSeconds: number;
    };
    RegisterRequest: {
      /** Format: email */
      email: string;
      /**
       * Format: password
       * @description Must contain at least one ASCII letter and one digit.
       */
      password: string;
      nickname: string;
      code: string;
    };
    LoginRequest: {
      /** Format: email */
      email: string;
      /** Format: password */
      password: string;
    };
    AdminCategory: {
      id: string;
      slug: string;
      name: string;
    };
    CurrentUser: {
      /** @description PostgreSQL bigint ID serialized as a string. */
      id: string;
      /** Format: email */
      email: string;
      nickname: string;
      /** @enum {string} */
      role: "USER" | "ADMIN";
      emailVerified: boolean;
      /** Format: date-time */
      createdAt: string;
      bio: string;
      /** Format: uuid */
      avatarFileId: string | null;
    };
    Error: {
      code: string;
      msg: string;
      data: null | {
        retryAfterSeconds: number;
      };
      /** Format: uuid */
      traceId: string;
    };
    Health: {
      /** @enum {string} */
      status: "UP";
      /** @enum {string} */
      database: "UP";
    };
    CreateCommentRequest: {
      /** @example PUBLICATION */
      targetType: string;
      /** @example ai-ppt-outline */
      targetKey: string;
      /**
       * Format: int64
       * @description 根评论的 id；省略则发表根评论
       */
      parentId?: number | null;
      body: string;
    };
    PublicationSummary: {
      /** @description PostgreSQL bigint ID serialized as a string. */
      id: string;
      slug: string;
      title: string;
      summary: string;
      categorySlug: string;
      categoryName: string;
      accessType: components["schemas"]["AccessType"];
      /** Format: date-time */
      publishedAt: string;
      publicationType: components["schemas"]["PublicationType"];
      /** Format: int64 */
      creditPrice: number;
      /** Format: uuid */
      coverFileId: string | null;
      /** @default false */
      featured: boolean;
    };
    PublicationDetail: {
      preview: components["schemas"]["Preview"];
      publication: components["schemas"]["PublicationSummary"];
    };
    PublicationContent: {
      markdown: string;
      version: string;
      /** Format: date-time */
      updatedAt: string;
      /** @description PostgreSQL bigint ID serialized as a string. */
      publicationId: string;
    };
    PublicationPage: {
      items: components["schemas"]["PublicationSummary"][];
      page: number;
      size: number;
      /** Format: int64 */
      total: number;
      /** Format: int64 */
      totalPages: number;
    };
    /** @description Article content snapshot. URL is assigned from the database ID after creation; clients cannot set or modify it. */
    AdminPublicationRequest: {
      /** Format: int64 */
      categoryId: number;
      title: string;
      summary: string;
      accessType: components["schemas"]["AccessType"];
      previewMarkdown: string;
      fullMarkdown: string;
      requirements: string;
      deliverables: string;
      version: string;
      publicationType: components["schemas"]["PublicationType"];
      /** Format: int64 */
      creditPrice: number;
      /** Format: uuid */
      coverFileId?: string | null;
      /** @default false */
      featured: boolean;
    };
    AdminPublicationSummary: {
      id: string;
      slug: string;
      title: string;
      categoryName: string;
      accessType: components["schemas"]["AccessType"];
      /** @enum {string} */
      status: "DRAFT" | "PUBLISHED" | "ARCHIVED";
      /** @enum {string} */
      deliveryStatus: "AVAILABLE" | "SUSPENDED";
      /** Format: date-time */
      publishedAt: string | null;
      /** Format: date-time */
      updatedAt: string;
      publicationType: components["schemas"]["PublicationType"];
      /** Format: int64 */
      creditPrice: number;
      /** Format: uuid */
      coverFileId: string | null;
      /** @default false */
      featured: boolean;
    };
    AdminPublicationDetail: {
      id: string;
      slug: string;
      title: string;
      accessType: components["schemas"]["AccessType"];
      /** @enum {string} */
      status: "DRAFT" | "PUBLISHED" | "ARCHIVED";
      /** @enum {string} */
      deliveryStatus: "AVAILABLE" | "SUSPENDED";
      /** Format: date-time */
      publishedAt: string | null;
      /** Format: date-time */
      updatedAt: string;
      publicationType: components["schemas"]["PublicationType"];
      /** Format: int64 */
      creditPrice: number;
      /** Format: uuid */
      coverFileId: string | null;
      /** @default false */
      featured: boolean;
      categoryId: string;
      summary: string;
      previewMarkdown: string;
      fullMarkdown: string;
      requirements: string;
      deliverables: string;
      version: string;
      /** Format: date-time */
      createdAt: string;
    };
    /** @enum {string} */
    PublicationType: "CASE_STUDY" | "ARTICLE" | "COURSE";
    /** @description 单条评论。大整数标识以字符串返回，避免前端丢精度。deleted 为真时 body 为空字符串，表示「该评论已删除」。 */
    CommentView: {
      id: string;
      /** @description 被回复的评论；回复一条回复时指向那条回复，用于显示「回复 @某人」 */
      parentId?: string | null;
      /** @description 所属根评论；根评论自身为 null */
      rootId?: string | null;
      /** @description 0 = 根评论，1 = 其下的回复；结构是单层的 */
      depth: number;
      authorId: string;
      authorName: string;
      /** @description 已删除的评论为空字符串 */
      body: string;
      likeCount: number;
      /** @description 当前登录用户是否点过赞；匿名访问恒为 false */
      likedByMe: boolean;
      deleted: boolean;
      /** @description 当前用户能否删除这条评论 */
      canDelete: boolean;
      /** Format: date-time */
      createdAt: string;
    };
    RootCommentView: {
      comment: components["schemas"]["CommentView"];
      /** @description 回复总数；大于 previewReplies 长度时前端显示「展开全部」 */
      replyCount: number;
      previewReplies: components["schemas"]["CommentView"][];
    };
    CommentPage: {
      items: components["schemas"]["RootCommentView"][];
      page: number;
      size: number;
      /** Format: int64 */
      total: number;
      totalPages: number;
    };
    ReplyPage: {
      items: components["schemas"]["CommentView"][];
      page: number;
      size: number;
      /** Format: int64 */
      total: number;
      totalPages: number;
    };
    LockThreadRequest: {
      /** @example PUBLICATION */
      targetType: string;
      /** @example ai-ppt-outline */
      targetKey: string;
    };
    /** @enum {string} */
    StoredFilePurpose: "AVATAR" | "ATTACHMENT";
    StoredFile: {
      /** Format: uuid */
      id: string;
      purpose: components["schemas"]["StoredFilePurpose"];
      filename: string;
      contentType: string;
      /** Format: int64 */
      size: number;
    };
    FileDownload: {
      /** Format: uri */
      url: string;
      /** Format: date-time */
      expiresAt: string;
    };
    UpdateProfile: {
      nickname: string;
      bio: string;
      /** Format: uuid */
      avatarFileId?: string | null;
    };
    AvatarImage: {
      /** Format: uri */
      url: string;
      /** Format: date-time */
      expiresAt: string;
    };
    Result: {
      /** @constant */
      code: "SUCCESS";
      msg: string;
      data: unknown;
      /** Format: uuid */
      traceId: string;
    };
    AdminMember: {
      id: string;
      email: string;
      nickname: string;
      /** @enum {string} */
      role: "ADMIN" | "USER";
      /** @enum {string} */
      status: "ACTIVE" | "DISABLED";
      emailVerified: boolean;
      /** Format: int64 */
      creditBalance: number;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      lastLoginAt: string | null;
    };
    MemberStatusRequest: {
      /** @enum {string} */
      status: "ACTIVE" | "DISABLED";
    };
    OperationsSummary: {
      /** Format: int64 */
      members: number;
      /** Format: int64 */
      activeMembers: number;
      /** Format: int64 */
      newMembers: number;
      /** Format: int64 */
      published: number;
      /** Format: int64 */
      drafts: number;
      /** Format: int64 */
      paid: number;
      /** Format: int64 */
      comments: number;
      /** Format: int64 */
      unlocks: number;
      /** Format: int64 */
      creditsSpent: number;
      /** Format: int64 */
      creditBalance: number;
    };
    OperationsDay: {
      /** Format: date */
      date: string;
      /** Format: int64 */
      registrations: number;
      /** Format: int64 */
      publications: number;
      /** Format: int64 */
      comments: number;
    };
    OperationsOverview: {
      summary: components["schemas"]["OperationsSummary"];
      days: components["schemas"]["OperationsDay"][];
    };
    LedgerEntry: {
      id: string;
      email: string;
      nickname: string;
      /** Format: int64 */
      delta: number;
      /** Format: int64 */
      balanceAfter: number;
      reason: string;
      note: string | null;
      /** Format: date-time */
      createdAt: string;
    };
    ModerationComment: {
      id: string;
      authorName: string;
      targetType: string;
      targetKey: string;
      title: string;
      body: string;
      status: string;
      threadStatus: string;
      /** Format: date-time */
      createdAt: string;
    };
    AdminMemberPage: {
      items: components["schemas"]["AdminMember"][];
      /** Format: int64 */
      page: number;
      /** Format: int64 */
      size: number;
      /** Format: int64 */
      total: number;
    };
    LedgerPage: {
      items: components["schemas"]["LedgerEntry"][];
      /** Format: int64 */
      page: number;
      /** Format: int64 */
      size: number;
      /** Format: int64 */
      total: number;
    };
    ModerationPage: {
      items: components["schemas"]["ModerationComment"][];
      /** Format: int64 */
      page: number;
      /** Format: int64 */
      size: number;
      /** Format: int64 */
      total: number;
    };
    PublicationMedia: {
      /** Format: uuid */
      id: string;
      /** @enum {string} */
      kind: "COVER" | "IMAGE" | "VIDEO" | "ATTACHMENT";
      filename: string;
      contentType: string;
      /** Format: int64 */
      size: number;
      url: string;
      /** Format: date-time */
      expiresAt: string;
    };
    PublicationUploadProgress: {
      /** @enum {string} */
      phase:
        | "RECEIVING"
        | "OSS"
        | "FINALIZING"
        | "COMPLETED"
        | "FAILED"
        | "CANCELLED";
      /**
       * Format: int64
       * @description Bytes acknowledged by OSS; retries do not increment this value.
       */
      loaded: number;
      /** Format: int64 */
      total: number;
    };
  };
  responses: {
    /** @description Invalid request */
    BadRequest: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Not signed in */
    Unauthorized: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Signed in without the ADMIN role */
    Forbidden: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Publication not found */
    NotFound: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Publication slug already exists */
    Conflict: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
  };
  parameters: {
    PublicationId: number;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      200: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            code: "SUCCESS";
            msg: string;
            data: components["schemas"]["Health"];
            /** Format: uuid */
            traceId: string;
          };
        };
      };
      /** @description Unexpected server error */
      500: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Database temporarily unavailable */
      503: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  sendEmailCode: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EmailCodeRequest"];
      };
    };
    responses: {
      /** @description Registration code request accepted */
      202: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            code: "SUCCESS";
            msg: string;
            data: components["schemas"]["EmailCodeDispatch"];
            /** Format: uuid */
            traceId: string;
          };
        };
      };
      /** @description Invalid email or purpose */
      400: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Code resend cooldown or rate limit reached */
      429: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Email delivery failed */
      503: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  register: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterRequest"];
      };
    };
    responses: {
      /** @description Account created; session cookie is set */
      201: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            code: "SUCCESS";
            msg: string;
            data: components["schemas"]["CurrentUser"];
            /** Format: uuid */
            traceId: string;
          };
        };
      };
      /** @description Invalid input or verification code */
      400: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Email already registered */
      409: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Registration rate limit reached */
      429: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Signed in; session cookie is set */
      200: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            code: "SUCCESS";
            msg: string;
            data: components["schemas"]["CurrentUser"];
            /** Format: uuid */
            traceId: string;
          };
        };
      };
      /** @description Invalid request */
      400: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Invalid credentials */
      401: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Login rate limit reached */
      429: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  getCurrentUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current member */
      200: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            code: "SUCCESS";
            msg: string;
            data: components["schemas"]["CurrentUser"];
            /** Format: uuid */
            traceId: string;
          };
        };
      };
      /** @description Not signed in */
      401: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success with an empty result */
      200: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            code: "SUCCESS";
            msg: string;
            data: null;
            /** Format: uuid */
            traceId: string;
          };
        };
      };
      /** @description Not signed in */
      401: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  getAdminCategories: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Category options */
      200: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            code: "SUCCESS";
            msg: string;
            data: components["schemas"]["AdminCategory"][];
            /** Format: uuid */
            traceId: string;
          };
        };
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
    };
  };
  getCategories: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      200: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            code: "SUCCESS";
            msg: string;
            data: components["schemas"]["Category"][];
            /** Format: uuid */
            traceId: string;
          };
        };
      };
      /** @description Unexpected server error */
      500: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Database temporarily unavailable */
      503: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  listComments: {
    parameters: {
      query: {
        targetType: string;
        targetKey: string;
        page?: number;
        size?: number;
        /** @description LATEST 按时间倒序；HOT 与 COMPREHENSIVE 按点赞数优先，后者以时间作为次级键 */
        sort?: "LATEST" | "HOT" | "COMPREHENSIVE";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 根评论分页 */
      200: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            code: "SUCCESS";
            msg: string;
            data: components["schemas"]["CommentPage"];
            /** Format: uuid */
            traceId: string;
          };
        };
      };
      /** @description 目标类型或分页参数不合法 */
      400: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description 目标不存在或未公开（草稿、下架、暂停交付） */
      404: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description 服务端异常 */
      500: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  createComment: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateCommentRequest"];
      };
    };
    responses: {
      /** @description 创建后的评论 */
      201: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            code: "SUCCESS";
            msg: string;
            data: components["schemas"]["CommentView"];
            /** Format: uuid */
            traceId: string;
          };
        };
      };
      /** @description 正文不符合要求 */
      400: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description 需要登录 */
      401: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description 目标或父评论不存在 */
      404: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description 讨论已锁定（DISCUSSION_THREAD_CLOSED），或被回复的评论已隐藏、已删除（COMMENT_NOT_REPLYABLE） */
      409: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description 服务端异常 */
      500: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  getAdminPublications: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description All publications */
      200: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            code: "SUCCESS";
            msg: string;
            data: components["schemas"]["AdminPublicationSummary"][];
            /** Format: uuid */
            traceId: string;
          };
        };
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
    };
  };
  createAdminPublication: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AdminPublicationRequest"];
      };
    };
    responses: {
      /** @description Draft created */
      201: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            code: "SUCCESS";
            msg: string;
            data: components["schemas"]["AdminPublicationDetail"];
            /** Format: uuid */
            traceId: string;
          };
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      409: components["responses"]["Conflict"];
    };
  };
  getAdminPublication: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["PublicationId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Editable publication */
      200: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            code: "SUCCESS";
            msg: string;
            data: components["schemas"]["AdminPublicationDetail"];
            /** Format: uuid */
            traceId: string;
          };
        };
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
    };
  };
  updateAdminPublication: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["PublicationId"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AdminPublicationRequest"];
      };
    };
    responses: {
      /** @description Publication updated */
      200: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            code: "SUCCESS";
            msg: string;
            data: components["schemas"]["AdminPublicationDetail"];
            /** Format: uuid */
            traceId: string;
          };
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
      409: components["responses"]["Conflict"];
    };
  };
  publishAdminPublication: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["PublicationId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Published publication */
      200: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            code: "SUCCESS";
            msg: string;
            data: components["schemas"]["AdminPublicationDetail"];
            /** Format: uuid */
            traceId: string;
          };
        };
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
    };
  };
  archiveAdminPublication: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["PublicationId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Archived publication */
      200: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            code: "SUCCESS";
            msg: string;
            data: components["schemas"]["AdminPublicationDetail"];
            /** Format: uuid */
            traceId: string;
          };
        };
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
    };
  };
  getPublications: {
    parameters: {
      query?: {
        page?: number;
        size?: number;
        q?: string;
        category?: string;
        access?: "" | "FREE" | "CREDIT";
        type?: "" | "CASE_STUDY" | "ARTICLE" | "COURSE";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      200: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            code: "SUCCESS";
            msg: string;
            data: components["schemas"]["PublicationPage"];
            /** Format: uuid */
            traceId: string;
          };
        };
      };
      /** @description Invalid query */
      400: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Unexpected server error */
      500: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Database temporarily unavailable */
      503: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  getPublication: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Canonical article ID, serialized as a decimal string. Existing legacy slug links remain readable for redirects. */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      200: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            code: "SUCCESS";
            msg: string;
            data: components["schemas"]["PublicationDetail"];
            /** Format: uuid */
            traceId: string;
          };
        };
      };
      /** @description Invalid slug */
      400: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Missing, draft, archived or suspended publication */
      404: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Unexpected server error */
      500: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Database temporarily unavailable */
      503: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  getPublicationContent: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      200: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            code: "SUCCESS";
            msg: string;
            data: components["schemas"]["PublicationContent"];
            /** Format: uuid */
            traceId: string;
          };
        };
      };
      /** @description Invalid ID */
      400: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Paid content is locked; purchases are not implemented */
      403: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Missing, draft, archived or suspended publication */
      404: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Unexpected server error */
      500: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Database temporarily unavailable */
      503: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  listReplies: {
    parameters: {
      query?: {
        page?: number;
        size?: number;
        /** @description LATEST 按时间倒序；HOT 与 COMPREHENSIVE 按点赞数优先，后者以时间作为次级键 */
        sort?: "LATEST" | "HOT" | "COMPREHENSIVE";
      };
      header?: never;
      path: {
        rootId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 回复分页 */
      200: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            code: "SUCCESS";
            msg: string;
            data: components["schemas"]["ReplyPage"];
            /** Format: uuid */
            traceId: string;
          };
        };
      };
      /** @description 分页参数不合法 */
      400: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description 根评论不存在、已隐藏，或其所在讨论与目标不可见 */
      404: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description 服务端异常 */
      500: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  toggleCommentLike: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 切换结果 */
      200: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            code: "SUCCESS";
            msg: string;
            data: {
              liked: boolean;
            };
            /** Format: uuid */
            traceId: string;
          };
        };
      };
      /** @description 需要登录 */
      401: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description 评论不存在或不可见 */
      404: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description 服务端异常 */
      500: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  deleteComment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success with an empty result */
      200: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            code: "SUCCESS";
            msg: string;
            data: null;
            /** Format: uuid */
            traceId: string;
          };
        };
      };
      /** @description 需要登录 */
      401: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description 不是作者本人，也不是管理员 */
      403: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description 评论不存在 */
      404: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description 服务端异常 */
      500: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  hideComment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success with an empty result */
      200: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            code: "SUCCESS";
            msg: string;
            data: null;
            /** Format: uuid */
            traceId: string;
          };
        };
      };
      /** @description 需要登录 */
      401: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description 需要管理员角色 */
      403: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description 评论不存在 */
      404: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description 服务端异常 */
      500: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  lockThread: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LockThreadRequest"];
      };
    };
    responses: {
      /** @description Success with an empty result */
      200: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            code: "SUCCESS";
            msg: string;
            data: null;
            /** Format: uuid */
            traceId: string;
          };
        };
      };
      /** @description 目标参数不合法 */
      400: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description 需要登录 */
      401: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description 需要管理员角色 */
      403: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description 目标不存在 */
      404: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description 服务端异常 */
      500: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  getFileDownloadUrl: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Temporary download URL; do not persist it */
      200: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            code: "SUCCESS";
            msg: string;
            data: components["schemas"]["FileDownload"];
            /** Format: uuid */
            traceId: string;
          };
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      404: components["responses"]["NotFound"];
      /** @description Storage unavailable */
      503: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  updateCurrentProfile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateProfile"];
      };
    };
    responses: {
      /** @description Profile saved */
      200: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            code: "SUCCESS";
            msg: string;
            data: components["schemas"]["CurrentUser"];
            /** Format: uuid */
            traceId: string;
          };
        };
      };
      /** @description Invalid profile */
      400: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Not signed in */
      401: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Account disabled */
      403: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Avatar file missing, foreign or wrong purpose */
      404: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Database temporarily unavailable */
      503: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  getCurrentAvatarImage: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Temporary image URL */
      200: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            code: "SUCCESS";
            msg: string;
            data: components["schemas"]["AvatarImage"];
            /** Format: uuid */
            traceId: string;
          };
        };
      };
      /** @description Not signed in */
      401: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Account disabled */
      403: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description No avatar */
      404: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Storage unavailable */
      503: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  uploadAvatar: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": {
          /** Format: binary */
          file: string;
        };
      };
    };
    responses: {
      /** @description Uploaded */
      201: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            code: "SUCCESS";
            msg: string;
            data: components["schemas"]["StoredFile"];
            /** Format: uuid */
            traceId: string;
          };
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      /** @description Multipart upload exceeds 20MB file or 21MB request limit */
      413: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Upload rate exceeded; retry after the indicated seconds */
      429: {
        headers: {
          "Retry-After"?: number;
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Storage unavailable */
      503: {
        headers: {
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  listAdminMembers: {
    parameters: {
      query?: {
        page?: number;
        size?: number;
        q?: string;
        status?: "" | "ACTIVE" | "DISABLED";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      200: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            code: "SUCCESS";
            msg: string;
            data: components["schemas"]["AdminMemberPage"];
            /** Format: uuid */
            traceId: string;
          };
        };
      };
      400: components["responses"]["Forbidden"];
      401: components["responses"]["Forbidden"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["Forbidden"];
      503: components["responses"]["Forbidden"];
    };
  };
  changeMemberStatus: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MemberStatusRequest"];
      };
    };
    responses: {
      /** @description Success */
      200: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            code: "SUCCESS";
            msg: string;
            data: components["schemas"]["AdminMember"];
            /** Format: uuid */
            traceId: string;
          };
        };
      };
      400: components["responses"]["Forbidden"];
      401: components["responses"]["Forbidden"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["Forbidden"];
      503: components["responses"]["Forbidden"];
    };
  };
  getOperationsOverview: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      200: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            code: "SUCCESS";
            msg: string;
            data: components["schemas"]["OperationsOverview"];
            /** Format: uuid */
            traceId: string;
          };
        };
      };
      400: components["responses"]["Forbidden"];
      401: components["responses"]["Forbidden"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["Forbidden"];
      503: components["responses"]["Forbidden"];
    };
  };
  listCreditLedger: {
    parameters: {
      query?: {
        page?: number;
        size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      200: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            code: "SUCCESS";
            msg: string;
            data: components["schemas"]["LedgerPage"];
            /** Format: uuid */
            traceId: string;
          };
        };
      };
      400: components["responses"]["Forbidden"];
      401: components["responses"]["Forbidden"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["Forbidden"];
      503: components["responses"]["Forbidden"];
    };
  };
  listModerationComments: {
    parameters: {
      query?: {
        page?: number;
        size?: number;
        status?: "" | "PUBLISHED" | "HIDDEN" | "DELETED";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      200: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            code: "SUCCESS";
            msg: string;
            data: components["schemas"]["ModerationPage"];
            /** Format: uuid */
            traceId: string;
          };
        };
      };
      400: components["responses"]["Forbidden"];
      401: components["responses"]["Forbidden"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["Forbidden"];
      503: components["responses"]["Forbidden"];
    };
  };
  uploadPublicationMedia: {
    parameters: {
      query?: {
        /** @description New client UUID per attempt; progress and cancellation are owner-scoped. */
        uploadId?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": {
          /** @enum {string} */
          kind: "COVER" | "IMAGE" | "VIDEO" | "ATTACHMENT";
          /** Format: binary */
          file: string;
        };
      };
    };
    responses: {
      /** @description Success */
      201: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            code: "SUCCESS";
            msg: string;
            data: components["schemas"]["PublicationMedia"];
            /** Format: uuid */
            traceId: string;
          };
        };
      };
      400: components["responses"]["Forbidden"];
      401: components["responses"]["Forbidden"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["Forbidden"];
      409: components["responses"]["Forbidden"];
      503: components["responses"]["Forbidden"];
    };
  };
  getAdminMediaUrl: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      200: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            code: "SUCCESS";
            msg: string;
            data: components["schemas"]["FileDownload"];
            /** Format: uuid */
            traceId: string;
          };
        };
      };
      400: components["responses"]["Forbidden"];
      401: components["responses"]["Forbidden"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["Forbidden"];
      503: components["responses"]["Forbidden"];
    };
  };
  getPublicationMediaUrl: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        publicationId: number;
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      200: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            code: "SUCCESS";
            msg: string;
            data: components["schemas"]["FileDownload"];
            /** Format: uuid */
            traceId: string;
          };
        };
      };
      400: components["responses"]["Forbidden"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["Forbidden"];
    };
  };
  getPublicationUploadProgress: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      200: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            code: "SUCCESS";
            msg: string;
            data: components["schemas"]["PublicationUploadProgress"];
            /** Format: uuid */
            traceId: string;
          };
        };
      };
      401: components["responses"]["Forbidden"];
      403: components["responses"]["Forbidden"];
    };
  };
  cancelPublicationUpload: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      200: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          /** @description Server-generated request trace ID; matches Result.traceId */
          "X-Trace-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            code: "SUCCESS";
            msg: string;
            data: null;
            /** Format: uuid */
            traceId: string;
          };
        };
      };
      401: components["responses"]["Forbidden"];
      403: components["responses"]["Forbidden"];
    };
  };
}
