/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Checks the actual PostgreSQL connection */
    get: operations["getHealth"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/email-codes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Sends a six-digit registration code through Resend */
    post: operations["sendEmailCode"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/register": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Creates a member account and signs it in */
    post: operations["register"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Signs in with email and password */
    post: operations["login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Returns the signed-in member */
    get: operations["getCurrentUser"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Invalidates the current session */
    post: operations["logout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/categories": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Lists category options for the content editor */
    get: operations["getAdminCategories"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/categories": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Categories with published and available publication counts */
    get: operations["getCategories"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/discussions/comments": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Returns the public nested comment tree for a registered target */
    get: operations["listComments"];
    put?: never;
    /** Creates a root comment or a reply as the logged-in member */
    post: operations["createComment"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/publications": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Lists publications in every publication state */
    get: operations["getAdminPublications"];
    put?: never;
    /** Creates a draft publication and its content */
    post: operations["createAdminPublication"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/publications/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["PublicationId"];
      };
      cookie?: never;
    };
    /** Returns the complete editable publication */
    get: operations["getAdminPublication"];
    /** Replaces the editable publication fields and content */
    put: operations["updateAdminPublication"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/publications/{id}/publish": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Publishes a publication to the public catalog */
    post: operations["publishAdminPublication"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/publications/{id}/archive": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Archives a publication and removes it from the public catalog */
    post: operations["archiveAdminPublication"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/publications": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Public publication summaries; never includes body content */
    get: operations["getPublications"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/publications/{slug}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Public detail and preview; never includes full body */
    get: operations["getPublication"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/publications/{id}/content": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Only published and available FREE publications are readable in M1 */
    get: operations["getPublicationContent"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @enum {string} */
    AccessType: "FREE" | "CREDIT";
    Category: {
      /** @description PostgreSQL bigint ID serialized as a string. */
      id: string;
      slug: string;
      name: string;
      /** Format: int64 */
      publicationCount: number;
    };
    Preview: {
      previewMarkdown: string;
      requirements: string;
      deliverables: string;
      version: string;
      /** Format: date-time */
      updatedAt: string;
    };
    EmailCodeRequest: {
      /** Format: email */
      email: string;
      /** @enum {string} */
      purpose: "REGISTER";
    };
    EmailCodeDispatch: {
      /** Format: int64 */
      expiresInSeconds: number;
      /** Format: int64 */
      resendAfterSeconds: number;
    };
    RegisterRequest: {
      /** Format: email */
      email: string;
      /**
       * Format: password
       * @description Must contain at least one ASCII letter and one digit.
       */
      password: string;
      nickname: string;
      code: string;
    };
    LoginRequest: {
      /** Format: email */
      email: string;
      /** Format: password */
      password: string;
    };
    AdminCategory: {
      id: string;
      slug: string;
      name: string;
    };
    CurrentUser: {
      /** @description PostgreSQL bigint ID serialized as a string. */
      id: string;
      /** Format: email */
      email: string;
      nickname: string;
      /** @enum {string} */
      role: "USER" | "ADMIN";
      emailVerified: boolean;
      /** Format: date-time */
      createdAt: string;
    };
    Error: {
      code: string;
      message: string;
      requestId: string;
    };
    Health: {
      /** @enum {string} */
      status: "UP";
      /** @enum {string} */
      database: "UP";
    };
    CreateCommentRequest: {
      /** @example PUBLICATION */
      targetType: string;
      /** @example free-publication */
      targetKey: string;
      /** Format: int64 */
      parentId?: number | null;
      body: string;
    };
    CommentNode: {
      id: string;
      parentId?: string | null;
      depth: number;
      authorId: string;
      authorName: string;
      body: string;
      /** Format: date-time */
      createdAt: string;
      replies: components["schemas"]["CommentNode"][];
    };
    PublicationSummary: {
      /** @description PostgreSQL bigint ID serialized as a string. */
      id: string;
      slug: string;
      title: string;
      summary: string;
      categorySlug: string;
      categoryName: string;
      accessType: components["schemas"]["AccessType"];
      /** Format: date-time */
      publishedAt: string;
      publicationType: components["schemas"]["PublicationType"];
      /** Format: int64 */
      creditPrice: number;
    };
    PublicationDetail: {
      preview: components["schemas"]["Preview"];
      publication: components["schemas"]["PublicationSummary"];
    };
    PublicationContent: {
      markdown: string;
      version: string;
      /** Format: date-time */
      updatedAt: string;
      /** @description PostgreSQL bigint ID serialized as a string. */
      publicationId: string;
    };
    PublicationPage: {
      items: components["schemas"]["PublicationSummary"][];
      page: number;
      size: number;
      /** Format: int64 */
      total: number;
      /** Format: int64 */
      totalPages: number;
    };
    AdminPublicationRequest: {
      /** Format: int64 */
      categoryId: number;
      slug: string;
      title: string;
      summary: string;
      accessType: components["schemas"]["AccessType"];
      previewMarkdown: string;
      fullMarkdown: string;
      requirements: string;
      deliverables: string;
      version: string;
      publicationType: components["schemas"]["PublicationType"];
      /** Format: int64 */
      creditPrice: number;
    };
    AdminPublicationSummary: {
      id: string;
      slug: string;
      title: string;
      categoryName: string;
      accessType: components["schemas"]["AccessType"];
      /** @enum {string} */
      status: "DRAFT" | "PUBLISHED" | "ARCHIVED";
      /** @enum {string} */
      deliveryStatus: "AVAILABLE" | "SUSPENDED";
      /** Format: date-time */
      publishedAt: string | null;
      /** Format: date-time */
      updatedAt: string;
      publicationType: components["schemas"]["PublicationType"];
      /** Format: int64 */
      creditPrice: number;
    };
    AdminPublicationDetail: components["schemas"]["AdminPublicationSummary"] & {
      categoryId: string;
      summary: string;
      previewMarkdown: string;
      fullMarkdown: string;
      requirements: string;
      deliverables: string;
      version: string;
      /** Format: date-time */
      createdAt: string;
    };
    /** @enum {string} */
    PublicationType: "CASE_STUDY" | "ARTICLE" | "COURSE";
  };
  responses: {
    /** @description Invalid request */
    BadRequest: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Not signed in */
    Unauthorized: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Signed in without the ADMIN role */
    Forbidden: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Publication not found */
    NotFound: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Publication slug already exists */
    Conflict: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
  };
  parameters: {
    PublicationId: number;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      200: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Health"];
        };
      };
      /** @description Unexpected server error */
      500: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Database temporarily unavailable */
      503: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  sendEmailCode: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EmailCodeRequest"];
      };
    };
    responses: {
      /** @description Registration code request accepted */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EmailCodeDispatch"];
        };
      };
      /** @description Invalid email or purpose */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Code resend cooldown or rate limit reached */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Email delivery failed */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  register: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterRequest"];
      };
    };
    responses: {
      /** @description Account created; session cookie is set */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CurrentUser"];
        };
      };
      /** @description Invalid input or verification code */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Email already registered */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Registration rate limit reached */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Signed in; session cookie is set */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CurrentUser"];
        };
      };
      /** @description Invalid request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Invalid credentials */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Login rate limit reached */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  getCurrentUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current member */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CurrentUser"];
        };
      };
      /** @description Not signed in */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Signed out */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not signed in */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  getAdminCategories: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Category options */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdminCategory"][];
        };
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
    };
  };
  getCategories: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      200: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Category"][];
        };
      };
      /** @description Unexpected server error */
      500: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Database temporarily unavailable */
      503: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  listComments: {
    parameters: {
      query: {
        targetType: string;
        targetKey: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Nested root comments and replies */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CommentNode"][];
        };
      };
      /** @description Invalid target */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Unexpected server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  createComment: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateCommentRequest"];
      };
    };
    responses: {
      /** @description Created comment node */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CommentNode"];
        };
      };
      /** @description Invalid comment body */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Login required */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Target or parent comment not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Discussion thread is locked */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Unexpected server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  getAdminPublications: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description All publications */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdminPublicationSummary"][];
        };
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
    };
  };
  createAdminPublication: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AdminPublicationRequest"];
      };
    };
    responses: {
      /** @description Draft created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdminPublicationDetail"];
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      409: components["responses"]["Conflict"];
    };
  };
  getAdminPublication: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["PublicationId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Editable publication */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdminPublicationDetail"];
        };
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
    };
  };
  updateAdminPublication: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["PublicationId"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AdminPublicationRequest"];
      };
    };
    responses: {
      /** @description Publication updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdminPublicationDetail"];
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
      409: components["responses"]["Conflict"];
    };
  };
  publishAdminPublication: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["PublicationId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Published publication */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdminPublicationDetail"];
        };
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
    };
  };
  archiveAdminPublication: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["PublicationId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Archived publication */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdminPublicationDetail"];
        };
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
    };
  };
  getPublications: {
    parameters: {
      query?: {
        page?: number;
        size?: number;
        q?: string;
        category?: string;
        access?: "" | "FREE" | "CREDIT";
        type?: "" | "CASE_STUDY" | "ARTICLE" | "COURSE";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      200: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PublicationPage"];
        };
      };
      /** @description Invalid query */
      400: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Unexpected server error */
      500: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Database temporarily unavailable */
      503: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  getPublication: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      200: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PublicationDetail"];
        };
      };
      /** @description Invalid slug */
      400: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Missing, draft, archived or suspended publication */
      404: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Unexpected server error */
      500: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Database temporarily unavailable */
      503: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  getPublicationContent: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      200: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PublicationContent"];
        };
      };
      /** @description Invalid ID */
      400: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Paid content is locked; purchases are not implemented */
      403: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Missing, draft, archived or suspended publication */
      404: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Unexpected server error */
      500: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Database temporarily unavailable */
      503: {
        headers: {
          "X-Request-Id"?: string;
          "Cache-Control"?: "no-store";
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
}
