/** Brand artwork from Lobe Icons / Simple Icons; see doc/ASSET_SOURCES.md. */
export const brands = [
  ["claude-color", "Claude", "#f4e8df"],
  ["openai", "ChatGPT", "#edf1eb"],
  ["gemini-color", "Gemini", "#eef0ff"],
  ["kimi-color", "Kimi", "#edf0ff"],
  ["ollama", "Ollama", "#f5f4f2"],
  ["deepseek-color", "DeepSeek", "#edf2ff"],
  ["qwen-color", "Qwen", "#f0edff"],
  ["doubao-color", "豆包", "#eef4f9"],
  ["cursor", "Cursor", "#eeeded"],
  ["perplexity-color", "Perplexity", "#eaf2ef"],
  ["midjourney", "Midjourney", "#f0f1f4"],
  ["kling-color", "可灵", "#eff5e6"],
  ["suno", "Suno", "#f9edef"],
  ["minimax-color", "MiniMax", "#fff1ee"],
  ["runway", "Runway", "#eceee9"],
  ["v0", "v0", "#eeeef0"],
  ["github", "GitHub", "#f1eef6"],
  ["notion", "Notion", "#f4f3ef"],
  ["figma", "Figma", "#f8eeee"],
  ["tiktok", "抖音", "#f0edf2"],
  ["xiaohongshu", "小红书", "#ffecef"],
] as const;
